"use strict";
exports.__esModule = true;
var Mobile_1 = require("./Mobile");
var MobileLibrary_1 = require("./MobileLibrary");
var Nokia3210 = new Mobile_1.Mobile("Nokia", "3210", "NokiaCompany", 60, "Azul", true, 1, 399);
var iPhone3G = new Mobile_1.Mobile("iPhone", "3g", "Apple", 20, "Gris", true, 6, 799);
var SamsungGalaxy10 = new Mobile_1.Mobile("Samsung", "Galaxy10", "SamsungCorp", 40, "Amarillo", false, 1, 599);
var SamsungGalaxy11 = new Mobile_1.Mobile("Samsung", "Galaxy10", "SamsungCorp", 40, "Amarillo", false, 1, 999);
var arrayMobiles = [Nokia3210, iPhone3G, SamsungGalaxy10, SamsungGalaxy11];
var mobileLibrarita = new MobileLibrary_1.MobileLibrary("The phone house", "Madrid", arrayMobiles);
mobileLibrarita.printLibrary();
